version: '3'

services:
  docker-neo-c:
    image: neo4j:3.5
    ports:
      - 7687:7687
      - 7474:7474

  godojo-c:
    image: godojo
    depends_on:
      - docker-neo-c
    ports:
      - 8081:8081


