version: '3'

services:
  docker-neo-sa:
    image: neo4j:3.5
    ports:
      - 7687:7687
      - 7474:7474

  godojo:
    image: com.greenasjade.j01/j01
    depends_on:
      - docker-neo-sa
    ports:
      - 8081:8081


